repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        name: check YAML
      - id: check-json
        name: check JSON
      - id: trailing-whitespace
        exclude: ^README.md$
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0  # âœ… Repositorio oficial (sin 'v')
    hooks:
      - id: isort
        language_version: python3.12
        entry: bash -c 'uv run isort --profile black "$@"' --
        types: [python]

  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.12
        entry: bash -c 'uv run black "$@"' --
        types: [python]

  - repo: local
    hooks:
      - id: run-tests
        name: Launch tests using pytest before push
        entry: bash -c "PYTHONPATH=. uv run pytest --tb=short -v --cov=src --cov-report=term-missing"
        language: system
        pass_filenames: false
        stages: [ pre-push ]
        always_run: true
        verbose: true
